language: node_js

node_js:
    - "node"

before_script:
    - npm install -g gulp
    - npm install -g typings
    - typings install

install:
- npm install --ignore-scripts

script:
    - gulp buildscript
